// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Task Grade', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Task Grade', async function() {
    await driver.setRect(1299, 741)
    {
      const dropdown = await driver.findElement(By.css(".input-lg"))
      await dropdown.findElement(By.xpath("//option[. = 'Credit']")).click()
    }
    {
      const element = await driver.findElement(By.css(".input-lg"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".input-lg"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".input-lg"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".input-lg")).click()
    {
      const dropdown = await driver.findElement(By.css(".input-lg"))
      await dropdown.findElement(By.xpath("//option[. = 'Distinction']")).click()
    }
    {
      const element = await driver.findElement(By.css(".input-lg"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".input-lg"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".input-lg"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".input-lg")).click()
    {
      const dropdown = await driver.findElement(By.css(".input-lg"))
      await dropdown.findElement(By.xpath("//option[. = 'High Distinction']")).click()
    }
    {
      const element = await driver.findElement(By.css(".input-lg"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".input-lg"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".input-lg"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".input-lg")).click()
  })
})
