angular.module('doubtfire.tasks.partials', [
  'doubtfire.tasks.partials.modals'
  'doubtfire.tasks.partials.student-unit-tasks'
  'doubtfire.tasks.partials.task-summary-stats'
  'doubtfire.tasks.partials.submit-task-form'
  'doubtfire.tasks.partials.task-plagiarism-report'
  'doubtfire.tasks.partials.task-sheet'
  'doubtfire.tasks.partials.task-feedback-directive'
  'doubtfire.tasks.partials.view-alignment-directive'
  'doubtfire.tasks.partials.tutor-task-feedback-view'
  'doubtfire.tasks.partials.provide-task-feedback'
  'doubtfire.tasks.partials.status-switcher'
  'doubtfire.tasks.partials.task-definition-selector'
  'doubtfire.tasks.partials.task-status-summary-stats'
  'doubtfire.tasks.partials.target-grade-stats'
  'doubtfire.tasks.partials.task-completion-stats'
])
