mod = angular.module("doubtfire.api.models", [
  require('./project')
  require('./unit')
  require('./unit-role')
  require('./user-role')
  require('./convenor')
  require('./tutor')
  require('./tutorial')
  require('./learning-alignments')
  require('./intended-learning-outcome')
  require('./task')
  require('./task-comment')
  require('./task-definition')
  require('./group-member')
  require('./group')
  require('./group-set')
  require('./task-alignment')
  require('./task-feedback')
  require('./task-similarity')
  require('./students')
  require('./user')
  require('./task-completion-csv')
  require('./portfolio-submission')
])

module.exports = mod.name
