// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class ReviewtaskextensionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void reviewtaskextension() {
    driver.get("http://localhost:4200/");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("tutor_1");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".list-group-item > .ng-binding")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".list-group-item > .ng-binding"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#task-key-student_0-A1 .list-group-item-heading")).click();
    driver.findElement(By.cssSelector(".cdk-focused")).click();
    driver.findElement(By.cssSelector(".mat-primary")).click();
    driver.findElement(By.cssSelector("#task-key-student_1-A21 .list-group-item-text")).click();
    driver.findElement(By.cssSelector(".mat-primary")).click();
    driver.findElement(By.cssSelector("#task-key-student_1-A11 .list-group-item-heading")).click();
    driver.findElement(By.cssSelector(".fail")).click();
    driver.findElement(By.cssSelector("#task-key-student_0-A21 .list-group-item-text")).click();
    driver.findElement(By.cssSelector(".ng-dirty")).click();
    driver.findElement(By.id("textField")).click();
    driver.findElement(By.cssSelector(".dropdown-user")).click();
    driver.findElement(By.linkText("Sign Out")).click();
    driver.close();
    driver.findElement(By.name("username")).click();
  }
}
