// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class StudentlistenrollinspectTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void studentlistenrollinspect() {
    driver.get("http://localhost:4200/");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("tutor_1");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".list-group-item > .ng-binding")).click();
    driver.findElement(By.cssSelector(".dropdown-toggle > .ng-binding:nth-child(1)")).click();
    driver.findElement(By.linkText("Student List")).click();
    driver.findElement(By.cssSelector(".pull-right > .btn:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) .form-control")).click();
    driver.findElement(By.cssSelector(".col-sm-7 > .ng-not-empty")).sendKeys("student_4");
    driver.findElement(By.id("searchbar")).click();
    driver.findElement(By.id("searchbar")).sendKeys("l");
    driver.findElement(By.linkText("LA1-01")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-primary"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Sign Out")).click();
  }
}
